// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type InternalWallet struct {
	WalletID          uuid.UUID `db:"wallet_id" json:"wallet_id"`
	DerivationVersion string    `db:"derivation_version" json:"derivation_version"`
	Index             int64     `db:"index" json:"index"`
}

type Wallet struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Address   string    `db:"address" json:"address"`
	Network   string    `db:"network" json:"network"`
	Asset     string    `db:"asset" json:"asset"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
