// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateInternalWallet(ctx context.Context, arg CreateInternalWalletParams) error
	CreateWallet(ctx context.Context, arg CreateWalletParams) error
	GetAllWallet(ctx context.Context, arg GetAllWalletParams) ([]Wallet, error)
	GetWallet(ctx context.Context, arg GetWalletParams) (GetWalletRow, error)
}

var _ Querier = (*Queries)(nil)
