// Copyright © 2017-2022 Trust Wallet.
//
// This file is part of Trust. The full Trust copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: TheOpenNetwork.proto

package theopennetwork

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "github.com/mamadeusia/WalletSrv/proto/tw/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletVersion int32

const (
	WalletVersion_WALLET_V3_R1 WalletVersion = 0
	WalletVersion_WALLET_V3_R2 WalletVersion = 1
	WalletVersion_WALLET_V4_R2 WalletVersion = 2
)

// Enum value maps for WalletVersion.
var (
	WalletVersion_name = map[int32]string{
		0: "WALLET_V3_R1",
		1: "WALLET_V3_R2",
		2: "WALLET_V4_R2",
	}
	WalletVersion_value = map[string]int32{
		"WALLET_V3_R1": 0,
		"WALLET_V3_R2": 1,
		"WALLET_V4_R2": 2,
	}
)

func (x WalletVersion) Enum() *WalletVersion {
	p := new(WalletVersion)
	*p = x
	return p
}

func (x WalletVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_TheOpenNetwork_proto_enumTypes[0].Descriptor()
}

func (WalletVersion) Type() protoreflect.EnumType {
	return &file_TheOpenNetwork_proto_enumTypes[0]
}

func (x WalletVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletVersion.Descriptor instead.
func (WalletVersion) EnumDescriptor() ([]byte, []int) {
	return file_TheOpenNetwork_proto_rawDescGZIP(), []int{0}
}

type SendMode int32

const (
	SendMode_DEFAULT                          SendMode = 0
	SendMode_PAY_FEES_SEPARATELY              SendMode = 1
	SendMode_IGNORE_ACTION_PHASE_ERRORS       SendMode = 2
	SendMode_DESTROY_ON_ZERO_BALANCE          SendMode = 32
	SendMode_ATTACH_ALL_INBOUND_MESSAGE_VALUE SendMode = 64
	SendMode_ATTACH_ALL_CONTRACT_BALANCE      SendMode = 128
)

// Enum value maps for SendMode.
var (
	SendMode_name = map[int32]string{
		0:   "DEFAULT",
		1:   "PAY_FEES_SEPARATELY",
		2:   "IGNORE_ACTION_PHASE_ERRORS",
		32:  "DESTROY_ON_ZERO_BALANCE",
		64:  "ATTACH_ALL_INBOUND_MESSAGE_VALUE",
		128: "ATTACH_ALL_CONTRACT_BALANCE",
	}
	SendMode_value = map[string]int32{
		"DEFAULT":                          0,
		"PAY_FEES_SEPARATELY":              1,
		"IGNORE_ACTION_PHASE_ERRORS":       2,
		"DESTROY_ON_ZERO_BALANCE":          32,
		"ATTACH_ALL_INBOUND_MESSAGE_VALUE": 64,
		"ATTACH_ALL_CONTRACT_BALANCE":      128,
	}
)

func (x SendMode) Enum() *SendMode {
	p := new(SendMode)
	*p = x
	return p
}

func (x SendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_TheOpenNetwork_proto_enumTypes[1].Descriptor()
}

func (SendMode) Type() protoreflect.EnumType {
	return &file_TheOpenNetwork_proto_enumTypes[1]
}

func (x SendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendMode.Descriptor instead.
func (SendMode) EnumDescriptor() ([]byte, []int) {
	return file_TheOpenNetwork_proto_rawDescGZIP(), []int{1}
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Wallet version
	WalletVersion WalletVersion `protobuf:"varint,1,opt,name=wallet_version,json=walletVersion,proto3,enum=TW.TheOpenNetwork.Proto.WalletVersion" json:"wallet_version,omitempty"`
	// Recipient address
	Dest string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// Amount to send in nanotons
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Message counter (optional, 0 by default used for the first deploy)
	// This field is required, because we need to protect the smart contract against "replay attacks"
	// Learn more: https://ton.org/docs/develop/smart-contracts/guidelines/external-messages
	SequenceNumber uint32 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Send mode (optional, 0 by default)
	// Learn more: https://ton.org/docs/develop/func/stdlib#send_raw_message
	Mode uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	// Expiration UNIX timestamp (optional, now() + 60 by default)
	ExpireAt uint32 `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// Transfer comment message (optional, empty by default)
	Comment string `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TheOpenNetwork_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_TheOpenNetwork_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_TheOpenNetwork_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetWalletVersion() WalletVersion {
	if x != nil {
		return x.WalletVersion
	}
	return WalletVersion_WALLET_V3_R1
}

func (x *Transfer) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Transfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Transfer) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Transfer) GetExpireAt() uint32 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Transfer) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SigningInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The secret private key used for signing (32 bytes).
	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// The payload transfer
	//
	// Types that are assignable to ActionOneof:
	//	*SigningInput_Transfer
	ActionOneof isSigningInput_ActionOneof `protobuf_oneof:"action_oneof"`
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TheOpenNetwork_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_TheOpenNetwork_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_TheOpenNetwork_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (m *SigningInput) GetActionOneof() isSigningInput_ActionOneof {
	if m != nil {
		return m.ActionOneof
	}
	return nil
}

func (x *SigningInput) GetTransfer() *Transfer {
	if x, ok := x.GetActionOneof().(*SigningInput_Transfer); ok {
		return x.Transfer
	}
	return nil
}

type isSigningInput_ActionOneof interface {
	isSigningInput_ActionOneof()
}

type SigningInput_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,2,opt,name=transfer,proto3,oneof"`
}

func (*SigningInput_Transfer) isSigningInput_ActionOneof() {}

// Transaction signing output.
type SigningOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Signed and base64 encoded BOC message
	Encoded string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// error code, 0 is ok, other codes will be treated as errors
	Error common.SigningError `protobuf:"varint,2,opt,name=error,proto3,enum=TW.Common.Proto.SigningError" json:"error,omitempty"`
	// error code description
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TheOpenNetwork_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_TheOpenNetwork_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_TheOpenNetwork_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetError() common.SigningError {
	if x != nil {
		return x.Error
	}
	return common.SigningError(0)
}

func (x *SigningOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_TheOpenNetwork_proto protoreflect.FileDescriptor

var file_TheOpenNetwork_proto_rawDesc = []byte{
	0x0a, 0x14, 0x54, 0x68, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x54, 0x57, 0x2e, 0x54, 0x68, 0x65, 0x4f, 0x70,
	0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x01,
	0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0e, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x26, 0x2e, 0x54, 0x57, 0x2e, 0x54, 0x68, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0c, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x3f, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x54, 0x57, 0x2e, 0x54, 0x68, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x42, 0x0e, 0x0a, 0x0c,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x83, 0x01, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x54, 0x57, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x45, 0x0a, 0x0d, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x56, 0x33,
	0x5f, 0x52, 0x31, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f,
	0x56, 0x33, 0x5f, 0x52, 0x32, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x41, 0x4c, 0x4c, 0x45,
	0x54, 0x5f, 0x56, 0x34, 0x5f, 0x52, 0x32, 0x10, 0x02, 0x2a, 0xb5, 0x01, 0x0a, 0x08, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c,
	0x54, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x41, 0x59, 0x5f, 0x46, 0x45, 0x45, 0x53, 0x5f,
	0x53, 0x45, 0x50, 0x41, 0x52, 0x41, 0x54, 0x45, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a,
	0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x48,
	0x41, 0x53, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x53, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17,
	0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x5f, 0x4f, 0x4e, 0x5f, 0x5a, 0x45, 0x52, 0x4f, 0x5f,
	0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x20, 0x12, 0x24, 0x0a, 0x20, 0x41, 0x54, 0x54,
	0x41, 0x43, 0x48, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x49, 0x4e, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x40, 0x12,
	0x20, 0x0a, 0x1b, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x80,
	0x01, 0x42, 0x17, 0x0a, 0x15, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x6a, 0x6e, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_TheOpenNetwork_proto_rawDescOnce sync.Once
	file_TheOpenNetwork_proto_rawDescData = file_TheOpenNetwork_proto_rawDesc
)

func file_TheOpenNetwork_proto_rawDescGZIP() []byte {
	file_TheOpenNetwork_proto_rawDescOnce.Do(func() {
		file_TheOpenNetwork_proto_rawDescData = protoimpl.X.CompressGZIP(file_TheOpenNetwork_proto_rawDescData)
	})
	return file_TheOpenNetwork_proto_rawDescData
}

var file_TheOpenNetwork_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_TheOpenNetwork_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TheOpenNetwork_proto_goTypes = []interface{}{
	(WalletVersion)(0),       // 0: TW.TheOpenNetwork.Proto.WalletVersion
	(SendMode)(0),            // 1: TW.TheOpenNetwork.Proto.SendMode
	(*Transfer)(nil),         // 2: TW.TheOpenNetwork.Proto.Transfer
	(*SigningInput)(nil),     // 3: TW.TheOpenNetwork.Proto.SigningInput
	(*SigningOutput)(nil),    // 4: TW.TheOpenNetwork.Proto.SigningOutput
	(common.SigningError)(0), // 5: TW.Common.Proto.SigningError
}
var file_TheOpenNetwork_proto_depIdxs = []int32{
	0, // 0: TW.TheOpenNetwork.Proto.Transfer.wallet_version:type_name -> TW.TheOpenNetwork.Proto.WalletVersion
	2, // 1: TW.TheOpenNetwork.Proto.SigningInput.transfer:type_name -> TW.TheOpenNetwork.Proto.Transfer
	5, // 2: TW.TheOpenNetwork.Proto.SigningOutput.error:type_name -> TW.Common.Proto.SigningError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TheOpenNetwork_proto_init() }
func file_TheOpenNetwork_proto_init() {
	if File_TheOpenNetwork_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TheOpenNetwork_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TheOpenNetwork_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TheOpenNetwork_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_TheOpenNetwork_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SigningInput_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TheOpenNetwork_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TheOpenNetwork_proto_goTypes,
		DependencyIndexes: file_TheOpenNetwork_proto_depIdxs,
		EnumInfos:         file_TheOpenNetwork_proto_enumTypes,
		MessageInfos:      file_TheOpenNetwork_proto_msgTypes,
	}.Build()
	File_TheOpenNetwork_proto = out.File
	file_TheOpenNetwork_proto_rawDesc = nil
	file_TheOpenNetwork_proto_goTypes = nil
	file_TheOpenNetwork_proto_depIdxs = nil
}
